### ISSUE TITLE
Customizing Authenticator

### ISSUE THREAD

**Issue by LutherDiaz** [go-chi/jwtauth#17]
When I use jwtauth.Authenticator, it works.
But when I copy the same Authenticator to my own package, an error occur at 
```
		if !ok || jwtToken == nil || !jwtToken.Valid {
			http.Error(w, http.StatusText(401), 401)
			return
		}
```

Any clues?

**Comment by LutherDiaz** [comment]
The jwt exists when I call `ctx.Value("jwt")`
But `ctx.Value("jwt").(*jwt.Token)` type cast seems to fail.

**Comment by pkieltyka** [comment]
@LutherDiaz I've introduced a new `jwtauth.TokenContext()` method to help retrieve the token object. Let me know.
