### ISSUE TITLE
Make token search order configureable

### ISSUE THREAD

**Issue by lukasmalkmus** [go-chi/jwtauth#19]
I think it would be nice to make the token search order configureable. Currently the middleware searches for a query parameter first. In my case, I would like to search for the token in the `Authorization` header only! Sure, I could create yet another fork, but maybe others want the same functionality. If this is desired, we could discuss this and I would look into submitting a PR.

**Comment by pkieltyka** [comment]
@lukasmalkmus sounds good, feel free to send a PR. I am going to be traveling for the next few weeks but please take a stab and keep it simple+clean.

**Comment by lukasmalkmus** [comment]
Take a look at #20.
