### ISSUE TITLE
gcloud build complaining about Encode

### ISSUE THREAD

**Issue by jrogozen** [go-chi/jwtauth#34]
google cloud builder is complaining for me when I use

`Encode(jwt.MapClaims{"UserID": user.ID})`

with the error

`cannot use jwt.MapClaims literal (type jwt.MapClaims) as type jwtauth.Claims`

looking here, https://github.com/go-chi/jwtauth/blob/master/jwtauth.go#L134 it seems like the Encode function is expecting jwt.Claims{} but based on example in the readme regarding token generation, that doesn't seem right

**Comment by philip-firstorder** [comment]
I get the same problem using https://github.com/codegangsta/gin

`[gin] Build failed
cannot use jwt.MapClaims literal (type jwt.MapClaims) as type jwtauth.Claims in argument jwtauth.Encode`

**Comment by acim** [comment]
I would say this is one of the breaking changes introduced in version 4 of jwtauth. Just pin it to version v3 or update your code.

https://github.com/go-chi/jwtauth/releases/tag/v4.0.0

**Comment by jrogozen** [comment]
upgrading to 4.0.0 fixed this. thanks
