### ISSUE TITLE
VerifyRequest returns incorrect error when error is due to ValidationErrorNotValidYet

### ISSUE THREAD

**Issue by 1gm** [go-chi/jwtauth#35]
In VerifyRequest the conditional statement checking the error returned by JWTAuth.Decode is performed against the wrong constant (assuming the comments in the code are correct)

```go
// lines 113-115 of jwtauth.go
} else if verr.Errors&jwt.ValidationErrorIssuedAt > 0 {
  return token, ErrNBFInvalid
}
```

should be 

```go
} else if verr.Errors&jwt.ValidationErrorNotValidYet > 0 {
  return token, ErrNBFInvalid
}
```

If this is not a bug (I haven't read the spec to know the difference between these errors) then my apologies for opening. I can send a PR over to address if interested.

Thanks

**Comment by carldunham** [comment]
Found this when staticcheck flagged to identical conditions in if/else

**Comment by hmkwizu** [comment]
Got same issue. submitted a PR #47

**Comment by pkieltyka** [comment]
solved in master
