### ISSUE TITLE
Repository Dead

### ISSUE THREAD

**Issue by n33pm** [go-chi/jwtauth#39]
looks like this repository is dead... no maintenance since jan.

**Comment by n33pm** [comment]
@pkieltyka, ok but whats about the pull requests?

**Comment by n33pm** [comment]
@pkieltyka ????

**Comment by pkieltyka** [comment]
the project is stable and I'll get to the pull requests when necessary. if you're unhappy you have three choices. 1. use another library 2. write your own 3. fork
