### ISSUE TITLE
jwtauth: token is expired 

### ISSUE THREAD

**Issue by akaDPR** [go-chi/jwtauth#48]
Eventhough , I set the exp time to 2 hours from now(). the Authenticator method throwing error.

**Comment by pkieltyka** [comment]
Thats a super weird one, I suspect something with underlying jwt library at jwt-go, perhaps value isn't being set correctly since it's triggering the wrong validation error in this case. Try out github.com/goware/jwtutil as a debug util to generate and test tokens locally

**Comment by pkieltyka** [comment]
solved in master
