### ISSUE TITLE
OIDC Discovery functionality

### ISSUE THREAD

**Issue by simongottschlag** [go-chi/jwtauth#63]
Hi!

I've been working on an extension for echo's JWT middleware to enable discovery through OpenID Connect. Everything using the jwx library.

Would you be interested in a PR for the same thing here?

You can see the PR here: https://github.com/labstack/echo-contrib/pull/59

If you are interested, I'd love some feedback on how you would prefer the API to be.

Thanks!

Regards,
Simon

**Comment by francesconi** [comment]
We are also be interested in this functionality. Since jwx is already used in the project this would be a great addition!

**Comment by simongottschlag** [comment]
@francesconi It's already supported 😊 Take a look at the oidchttp package: https://github.com/XenitAB/go-oidc-middleware
