### ISSUE TITLE
Error with using Claims type as Map

### ISSUE THREAD

**Issue by enoposix** [go-chi/jwtauth#7]
Running the example gives the following error:

```
# github.com/goware/jwtauth
../github.com/goware/jwtauth/jwtauth.go:151: cannot use claims (type Claims) as type jwt.Claims in assignment:
        Claims does not implement jwt.Claims (missing Valid method)
../github.com/goware/jwtauth/jwtauth.go:173: invalid operation: t.Claims["exp"] (type jwt.Claims does not support indexing)
../github.com/goware/jwtauth/jwtauth.go:175: use of .(type) outside type switch
```

**Comment by pkieltyka** [comment]
thanks for the heads up. Looks to be that https://github.com/dgrijalva/jwt-go has released v3.0 with a few breaking changes.

**Comment by pkieltyka** [comment]
I suggest to vendor https://github.com/dgrijalva/jwt-go/tree/v2.7.0 as jwt-go v3.0 is very new, and are a few outstanding issues before I can upgrade this package

**Comment by JesseObrien** [comment]
Any movement on this?

**Comment by pkieltyka** [comment]
@JesseObrien not at this time, but PRs are welcome. jwt-go 2.7.0 works just fine, is there a particular reason you need 3.0?

**Comment by pkieltyka** [comment]
done, jwtauth latest version supports jwt-go v3
