### ISSUE TITLE
Claims["sub"] causing 401 token unauthorized error

### ISSUE THREAD

**Issue by kein-1** [go-chi/jwtauth#94]
Hi, 

Using a claims["sub"] causes a token verification failure; funny enough, if i use something like "ids" or even "ids123" below, it works fine. Any reason why this is the issue? I read through the source code and it does not seem to be looking for that specific error

```
func GenerateJWT(user *types.User) (string, error) {
	key := []byte(config.ConfigValues.SECRET_KEY)

	claims := jwt.MapClaims{}
	claims["id"] = user.ID
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenStr, err := token.SignedString(key)
	if err != nil {
		return "", err
	}
	return tokenStr, err
}
```

**Comment by VojtechVitek** [comment]
https://www.jakeworth.com/posts/til-what-is-the-jwt-sub/
